import * as Yup from 'yup';

export const SizeMeasurementSchema = Yup.object().shape({
    Measurement1: Yup.string().required('Name is required'),
    SizeOptionId: Yup.string().required('Size Option is required'),
    ClientId: Yup.string().required('Client is required'),
    // FrontLengthHPS: Yup.string().required('Field is required'),
    // BackLengthHPS: Yup.string().required('Field is required'),
    // AcrossShoulders: Yup.string().required('Field is required'),
    // ArmHole: Yup.string().required('Field is required'),
    // UpperChest: Yup.string().required('Field is required'),
    // LowerChest: Yup.string().required('Field is required'),
    // Waist: Yup.string().required('Field is required'),
    // BottomWidth: Yup.string().required('Name is required'),
    // SleeveLength: Yup.string().required('Field is required'),
    // SleeveOpening: Yup.string().required('Field is required'),
    // NeckSize: Yup.string().required('Field is required'),
    // CollarHeight: Yup.string().required('Field is required'),
    // CollarPointHeight: Yup.string().required('Field is required'),
    // StandHeightBack: Yup.string().required('Field is required'),
    // CollarStandLength: Yup.string().required('Field is required'),
    // SideVentFront: Yup.string().required('Field is required'),
    // SideVentBack: Yup.string().required('Field is required'),
    // PlacketLength: Yup.string().required('Field is required'),
    // TwoButtonDistance: Yup.string().required('Field is required'),
    // PlacketWidth: Yup.string().required('Field is required'),
    // BottomHem: Yup.string().required('Field is required'),
})