import type { Config } from "tailwindcss";
const {heroui} = require("@heroui/react");

const config: Config = {
   darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      '2xsm': '375px',
      'xsm': '425px', 
      'sm': '640px', 
      'md': '768px', 
      'lg': '1024px',  
      'xl': '1280px',  
      '2xl': '1536px', 
      '3xl': '2000px', 
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        brand: {
          25: 'rgb(var(--color-brand-25) / <alpha-value>)',
          50: 'rgb(var(--color-brand-50) / <alpha-value>)',
          100: 'rgb(var(--color-brand-100) / <alpha-value>)',
          200: 'rgb(var(--color-brand-200) / <alpha-value>)',
          300: 'rgb(var(--color-brand-300) / <alpha-value>)',
          400: 'rgb(var(--color-brand-400) / <alpha-value>)',
          500: 'rgb(var(--color-brand-500) / <alpha-value>)',
          600: 'rgb(var(--color-brand-600) / <alpha-value>)',
          700: 'rgb(var(--color-brand-700) / <alpha-value>)',
          800: 'rgb(var(--color-brand-800) / <alpha-value>)',
          900: 'rgb(var(--color-brand-900) / <alpha-value>)',
          950: 'rgb(var(--color-brand-950) / <alpha-value>)',
        },
        gray: {
          25: 'var(--color-gray-25)',
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
          950: 'var(--color-gray-950)',
          dark: 'var(--color-gray-dark)',
        },
        error:{
          25: 'var(--color-error-25)',
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
          950: 'var(--color-error-950)',
        },
      },
      fontFamily: {
        outfit: ['Outfit', 'sans-serif'],
      },
      fontSize: {
        'title-2xl': ['var(--text-title-2xl)', 'var(--text-title-2xl--line-height)'],
        'title-xl': ['var(--text-title-xl)', 'var(--text-title-xl--line-height)'],
        'title-lg': ['var(--text-title-lg)', 'var(--text-title-lg--line-height)'],
        'title-md': ['var(--text-title-md)', 'var(--text-title-md--line-height)'],
        'title-sm': ['var(--text-title-sm)', 'var(--text-title-sm--line-height)'],
        'theme-xl': ['var(--text-theme-xl)', 'var(--text-theme-xl--line-height)'],
        'theme-sm': ['var(--text-theme-sm)', 'var(--text-theme-sm--line-height)'],
        'theme-xs': ['var(--text-theme-xs)', 'var(--text-theme-xs--line-height)'],
      },
      zIndex: {
        '1': '1',
        '9': '9',
        '99': '99',
        '999': '999',
        '9999': '9999',
        '99999': '99999',
        '999999': '999999',
      },
      boxShadow: {
        'theme-md':'var(--shadow-theme-md)',
        'theme-lg': 'var(--shadow-theme-lg)',
        'theme-sm': 'var(--shadow-theme-sm)',
        'theme-xs': 'var(--shadow-theme-xs)',
        'theme-xl': 'var(--shadow-theme-xl)',
        'datepicker': 'var(--shadow-datepicker)',
        'focus-ring': 'var(--shadow-focus-ring)',
        'slider-navigation': 'var(--shadow-slider-navigation)',
        'tooltip': 'var(--shadow-tooltip)',
      },
    },
  },
  plugins: [heroui()],
} 
export default config satisfies Config;
