export const defaultMeasurementValues = {
  SizeOptionId: 0,
  ClientId: 0,
  Measurement1: "",
  ProductCategoryId: "",

  // Top unit
  BackNeckDrop: "",
  FrontNeckDrop: "",
  ShoulderSeam: "",
  ShoulderSlope: "",
  UpperChest: "",
  LowerChest: "",
  SleeveLength: "",
  SleeveOpening: "",
  ArmHole: "",
  FrontLengthHPS: "",
  FrontRise: "",
  BottomHem: "",
  NeckSize: "",
  Neckwidth: "",
  CollarHeight: "",
  CollarPointHeight: "",
  CollarStandLength: "",
  ColllarHeightCenterBack: "",
  CollarOpening: "",
  ArmHoleStraight: "",
  AcrossShoulders: "",
  BackLengthHPS: "",
  BottomWidth: "",
  BottomRib: "",
  StandHeightBack: "",
  SideVentFront: "",
  SideVentBack: "",
  PlacketLength: "",
  TwoButtonDistance: "",
  Hem: "",
  PlacketWidth: "",

  // Bottom unit
  Hip: "",
  Waist: "",
  WasitStretch: "",
  WasitRelax: "",
  Thigh: "",
  bFrontRise: "",
  BackRise: "",
  TotalLength: "",
  WBHeight: "",
  bBottomWidth: "",
  BottomOriginal: "",
  BottomElastic: "",
  BottomCuffZipped: "",
  BottomStraightZipped: "",
  Outseam: "",
  Inseam: "",
  HemBottom: "",
  KneeWidth: "",
  LegOpening: "",

  // Logo placement - Top
  t_TopRight: "",
  t_TopLeft: "",
  t_BottomRight: "",
  t_BottomLeft: "",
  t_Back: "",
  t_Center: "",
  t_left_sleeve: "",
  t_right_sleeve: "",

  // Logo placement - Bottom
  b_TopRight: "",
  b_TopLeft: "",
  b_BottomRight: "",
  b_BottomLeft: "",

  // Bag Unit
  Bag_Height: "",
  Bag_Length: "",
  Bag_Depth: "",
  Bag_HandleGrip: "",
  Bag_ShoulderStrap_Full_Length: "",
  Bag_FrontPocketLength: "",
  Bag_FrontPocketHeight: "",
  Bag_SidePocketLength: "",
  Bag_SidePocketHeight: "",
};

export enum UnitType {
  None = 0,
  Top = 1,
  Bottom = 2,
  Logo = 3,
  Hat = 4,
  Bag = 5,
}
