CREATE TABLE `OrderEvent` (
    `Id` INT AUTO_INCREMENT PRIMARY KEY,
    `EventName` VARCHAR(255) NOT NULL UNIQUE,
    `Description` TEXT,
    `CreatedOn` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CreatedBy` VARCHAR(100),
    `UpdatedOn` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `UpdatedBy` VARCHAR(100)
);
