CREATE TABLE OrderItemColors (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ProductId INT NOT NULL,
    ColorOptionId INT NOT NULL,
    OrderItemId INT NOT NULL,
    CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR(100),
    UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(100),
    FOREIGN KEY (ProductId) REFERENCES Product(Id) ON DELETE RESTRICT,
    FOREIGN KEY (ColorOptionId) REFERENCES AvailableColorOptions(Id) ON DELETE RESTRICT,
    FOREIGN KEY (OrderItemId) REFERENCES OrderItems(Id) ON DELETE CASCADE
);